### PR TITLE
:bug: added apigen install in makefile tools section, added references to u…

### LINKED ISSUE #140: feature: `make crds` should include APIExport generation
### Feature Description

edge-mc should have the functional equivalent of https://github.com/kcp-dev/kcp/blob/cb8dd3c46470f30414c6789be956162ccb21f669/hack/update-codegen-crds.sh#L55-L58 --- ideally without maintaining a copy of the apigen tool.

### Proposed Solution

Have the Makefile or a script `go install github.com/kcp-dev/kcp/cmd/apigen@$right_version` into some tools binary directory and invoke it from there.  https://github.com/kcp-dev/kcp/pull/2669 has merged and this makes it possible to `go install` apigen.

I just tested the apigen from kcp commit cb8dd3c46470f30414c6789be956162ccb21f669 and it produced exactly the same output as the apigen binary that I built earlier from kcp commit 4506fdc06406 (which is the one that edge-mc currently depends on).

### Alternative Solutions

- Maintain a copy of the apigen source.
- Have the Makefile or script `git clone` kcp to get the source and then build it.

### Want to contribute?

- [x] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by clubanderson**
added apigen install in makefile tools section, added references to update-go-modules and verify-go-modules but commented them out for now, and updated update-codegen-crds to run apigen against crds and place them into ./config/exports

## Related issue(s)

Fixes #140

### CODE REVIEW

File: hack/update-codegen-crds.sh [hunk 1]
```diff
@@ -17,24 +17,27 @@
...
-for CRD in ./config/crds/*.yaml; do
+(
+    cd "${REPO_ROOT}/pkg/apis"
+    "../../${CONTROLLER_GEN}" \
+        crd \
+        rbac:roleName=manager-role \
+        webhook \
+        paths="./..." \
+        output:crd:artifacts:config="${REPO_ROOT}"config/crds
+)
```
Comment (MikeSpreitzer) [inline hack/update-codegen-crds.sh:38]: Nothing later depends on what is the current working directory at this point, if I follow correctly; that makes the subshell unnecessary.

File: hack/update-codegen-crds.sh [hunk 2]
```diff
@@ -46,7 +49,7 @@ done
 #     crd \
 #     rbac:roleName=manager-role \
 #     webhook \
-#     paths="./test/e2e/reconciler/cluster/..." \
-#     output:crd:artifacts:config=test/e2e/reconciler/cluster/
+#     paths="${REPO_ROOT}/test/e2e/reconciler/cluster/..." \
+#     output:crd:artifacts:config="${REPO_ROOT}"/test/e2e/reconciler/cluster/
 
-# go run ./cmd/apigen --input-dir ./config/crds --output-dir  ./config/root-phase0
+"${REPO_ROOT}"/hack/tools/apigen --input-dir "${REPO_ROOT}"/config/crds --output-dir "${REPO_ROOT}"/config/exports
```
Comment (MikeSpreitzer) [inline hack/update-codegen-crds.sh:55]: What happened to the version number in that binary name?
Don't you mean to use `$API_GEN` ?

File: hack/update-codegen-crds.sh [hunk 3]
```diff
@@ -17,24 +17,27 @@
 set -o errexit
 set -o nounset
 set -o pipefail
-# set -o xtrace
+set -o xtrace
 
-if [[ -z "${MAKELEVEL:-}" ]]; then
-    echo 'You must invoke this script via make'
+if [[ -z "${CONTROLLER_GEN:-}" ]]; then
```
Comment (MikeSpreitzer) [inline hack/update-codegen-crds.sh:22]: There's also `$API_GEN`, right?

File: hack/update-codegen-crds.sh [hunk 4]
```diff
@@ -17,24 +17,27 @@
...
+    echo "You must either set CONTROLLER_GEN to the path to controller-gen or invoke via make"
```
Comment (MikeSpreitzer) [inline hack/update-codegen-crds.sh:23]: Since invoking by make sets that envar, these are not mutually exclusive.  They do not have to be mutually exclusive, but the reader might infer that you think they are.  How about something like "\$CONTROLLER_GEN must be defined to refer to the right binary, e.g. as is done in the Makefile"?

**Comment by MikeSpreitzer** [comment]
Also, I do not see benefit in introducing scripts that are not used.

File: hack/update-go-modules.sh [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+set -o pipefail
+
+REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
+
+mapfile -t DIRS < <(find "${REPO_ROOT}" -name go.mod -print0 | xargs -0 dirname)
+
+for dir in "${DIRS[@]}"; do
+  echo "Tidying ${dir}"
+  go mod tidy
+done
```
Comment (MikeSpreitzer) [inline hack/update-go-modules.sh:30]: Please terminate the last line with a newline.  This is a general rule that seems to be preferred in open source work.

File: hack/update-codegen-crds.sh (hunk 2 above)
Comment (clubanderson) [reply hack/update-codegen-crds.sh:55]: 'apigen' is logical linked to the fully qualified apigen binary that includes the version number in the name.

File: hack/update-codegen-crds.sh (hunk 3 above)
Comment (clubanderson) [reply hack/update-codegen-crds.sh:22]: added check for API_GEN

File: hack/update-codegen-crds.sh (hunk 4 above)
Comment (clubanderson) [reply hack/update-codegen-crds.sh]: changed comment as requested

File: hack/update-codegen-crds.sh (hunk 2 above)
Comment (clubanderson) [reply hack/update-codegen-crds.sh]: I changed run line to use ${API_GEN} which includes path and version number in name

File: hack/update-codegen-crds.sh (hunk 1 above)
Comment (clubanderson) [reply hack/update-codegen-crds.sh]: removed

**Comment by clubanderson** [comment]
@MikeSpreitzer changes made according to your commits, please review again.

File: hack/verify-go-modules.sh [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+
+set -o errexit
+set -o nounset
+set -o pipefail
+
+REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
+
+mapfile -t DIRS < <(find "${REPO_ROOT}" -name go.mod -print0 | xargs -0 dirname)
+
+for dir in "${DIRS[@]}"; do
```
Comment (MikeSpreitzer) [inline hack/verify-go-modules.sh:27]: This is a lot of logic for not much good.

```
bash-5.1$ find . -name go.mod
./ta
ste/go.mod
./go.mod
./docs/go.mod
./te  st/go.mod
./pkg/apis/go.mod

bash-5.1$ mapfile -t DIRS < <(find . -name go.mod -print0 | xargs -0 dirname)

bash-5.1$ for dir in "${DIRS[@]}"; do echo working on "($dir)"; done
working on (./ta)
working on (ste)
working on (.)
working on (./docs)
working on (./te  st)
working on (./pkg/apis)
```

Comment (MikeSpreitzer) [reply hack/verify-go-modules.sh:27]: cf

```
bash-5.1$ cat > process.sh
echo "Working on (${1#go.mod})"

bash-5.1$ chmod a+x process.sh

bash-5.1$ find . -name go.mod -exec $PWD/process.sh \{\} \;
Working on (./ta
ste/go.mod)
Working on (./go.mod)
Working on (./docs/go.mod)
Working on (./te  st/go.mod)
Working on (./pkg/apis/go.mod)
```

Comment (MikeSpreitzer) [reply hack/verify-go-modules.sh:27]: cf

```
bash-5.1$ cat > process.sh
#!/usr/bin/env bash
echo "Working on (${1%/go.mod})"
bash-5.1$ 
bash-5.1$ chmod a+x process.sh
bash-5.1$ find . -name go.mod -exec $PWD/process.sh \{\} \;
Working on (./ta
ste)
Working on (.)
Working on (./docs)
Working on (./te  st)
Working on (./pkg/apis)
```

File: hack/update-go-modules.sh [hunk 7]
```diff
@@ -0,0 +1,30 @@
+#!/usr/bin/env bash
```
[the remark this answers is not in the document]
Comment (clubanderson) [reply hack/update-go-modules.sh]: removed

File: hack/verify-go-modules.sh (hunk 6 above)
Comment (clubanderson) [reply hack/verify-go-modules.sh]: removed file altogether since it is not being used

**Comment by clubanderson** [comment]
unreferenced scripts have been removed as well as references in makefile to them.  Ready for your review @MikeSpreitzer

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
